Feat: add sso_auth parameter
disc/terraform-provider-pritunl pull request #45
Opened 2023-09-06 20:31 UTC by QuentinBtd

### Why ?
`sso_auth` parameter exists in Priutnl servers. 
When set at `true`, it will require client to authenticate with single sign-on provider on each connection using web browser.
It could be usefull to have it. (And I need it, of course)

### How ?
Adding it in provider.

2023-09-08 08:54 UTC, QuentinBtd commented
Hello @disc 👋

2023-09-09 12:39 UTC, disc commented
Hey @QuentinBtd, i appreciate your contribution, but I think it won't work without configuration of SSO settings for the whole pritunl instance (see the attached screenshot). 
<img width="946" alt="image" src="https://github.com/disc/terraform-provider-pritunl/assets/306231/140aa9c1-edab-4fcb-83db-5e0b0d509442">

I started to work on the instance settings some time ago [here](https://github.com/disc/terraform-provider-pritunl/pull/14) () but haven't completed it yet.

2023-09-09 15:39 UTC, QuentinBtd commented
Do you think Pritunl will return an error if the provider send a JSON with `sso_auth` in, while SSO is not configured at the instance level? 

I could try it with an instance where SSO is not configured 😃

2023-09-09 16:21 UTC, disc commented
I meant it won't work without a configuration of SSO for the entire server, but the options sso_auth will be saved and will open browser each time with 404 page due to empty SSO settings.

<img width="722" alt="image" src="https://github.com/disc/terraform-provider-pritunl/assets/306231/2b8ea5f5-5816-4150-b90e-22f39621d2a7">

This feature could not be useful if you manually setup SSO on the server but manage the `sso_auth` option with terraform, don't you think so?

2023-09-09 16:33 UTC, QuentinBtd commented
> This feature could not be useful if you manually setup SSO on the server but manage the `sso_auth` option with terraform, don't you think so?

That's exactly what I want to do 👍 

The SSO configuration is already present on my instance. My servers are provisioned via Terraform but I have to manually check `sso_auth` after each apply terraform because this action unchecks it 😢

2023-09-09 16:35 UTC, disc requested changes

2023-09-09 16:35 UTC, disc commented on internal/pritunl/server.go
> +	SsoAuth          bool     `json:"sso_auth"`
Add `omitempty`

2023-09-09 16:35 UTC, disc commented on internal/provider/resource_server.go
> +			"sso_auth": {
Add test case for a new option

2023-09-09 16:36 UTC, disc commented
> > This feature could not be useful if you manually setup SSO on the server but manage the `sso_auth` option with terraform, don't you think so?
> 
> That's exactly what I want to do 👍
> 
> The SSO configuration is already present on my instance. My servers are provisioned via Terraform but I have to manually check `sso_auth` after each apply terraform because this action unchecks it 😢

For 

> > This feature could not be useful if you manually setup SSO on the server but manage the `sso_auth` option with terraform, don't you think so?
> 
> That's exactly what I want to do 👍
> 
> The SSO configuration is already present on my instance. My servers are provisioned via Terraform but I have to manually check `sso_auth` after each apply terraform because this action unchecks it 😢

Got you, lets add a test for the new option and fix small issues that I left.

2023-09-14 14:20 UTC, disc commented
@QuentinBtd I'm going to close this PR as a duplicate, because I've just merged another PR with support of the same feature
https://github.com/disc/terraform-provider-pritunl/pull/48/

2023-09-14 14:20 UTC, closed without merging

2023-09-14 15:59 UTC, QuentinBtd commented
No problem
@SwissGipfel was more fast than me, or have more time, but thank you ❤️